// GENERATED BY tooling/sync_emoticons.mjs — do not edit by hand.
// ignore_for_file: constant_identifier_names

const Map<String, String> kEmoticonOfflineAssetById = <String, String>{

};

const Map<String, String> kEmoticonOfflineAssetByImageUrl = <String, String>{

};

const Map<String, String> kEmoticonPackThumbOfflineById = <String, String>{

};
