-- 오라클 80종: 상점 표시명·썸네일 URL 패치 (gggom0505.kr / Flutter 웹 공통)
-- SQL 에디터에서 실행. id 기준으로만 갱신(가격 등 다른 컬럼은 유지).
-- DB에 행이 없으면 앱이 번들 카탈로그를 쓰고, 행이 있으면 여기 값이 노출됩니다.

UPDATE shop_items SET name = '01. 성운', thumbnail_url = 'oracle_cards/oracle(1).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-01';
UPDATE shop_items SET name = '02. 북극성', thumbnail_url = 'oracle_cards/oracle(2).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-02';
UPDATE shop_items SET name = '03. 초승달', thumbnail_url = 'oracle_cards/oracle(3).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-03';
UPDATE shop_items SET name = '04. 보름달', thumbnail_url = 'oracle_cards/oracle(4).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-04';
UPDATE shop_items SET name = '05. 유성우', thumbnail_url = 'oracle_cards/oracle(5).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-05';
UPDATE shop_items SET name = '06. 태양풍', thumbnail_url = 'oracle_cards/oracle(6).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-06';
UPDATE shop_items SET name = '07. 은하의 문', thumbnail_url = 'oracle_cards/oracle(7).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-07';
UPDATE shop_items SET name = '08. 일식', thumbnail_url = 'oracle_cards/oracle(8).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-08';
UPDATE shop_items SET name = '09. 안드로메다', thumbnail_url = 'oracle_cards/oracle(9).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-09';
UPDATE shop_items SET name = '10. 황도대', thumbnail_url = 'oracle_cards/oracle(10).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-10';
UPDATE shop_items SET name = '11. 초신성', thumbnail_url = 'oracle_cards/oracle(11).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-11';
UPDATE shop_items SET name = '12. 블랙홀', thumbnail_url = 'oracle_cards/oracle(12).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-12';
UPDATE shop_items SET name = '13. 화이트홀', thumbnail_url = 'oracle_cards/oracle(13).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-13';
UPDATE shop_items SET name = '14. 오로라', thumbnail_url = 'oracle_cards/oracle(14).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-14';
UPDATE shop_items SET name = '15. 혜성', thumbnail_url = 'oracle_cards/oracle(15).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-15';
UPDATE shop_items SET name = '16. 성단', thumbnail_url = 'oracle_cards/oracle(16).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-16';
UPDATE shop_items SET name = '17. 우주먼지', thumbnail_url = 'oracle_cards/oracle(17).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-17';
UPDATE shop_items SET name = '18. 정지된 궤도', thumbnail_url = 'oracle_cards/oracle(18).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-18';
UPDATE shop_items SET name = '19. 웜홀', thumbnail_url = 'oracle_cards/oracle(19).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-19';
UPDATE shop_items SET name = '20. 창조의 기둥', thumbnail_url = 'oracle_cards/oracle(20).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-20';
UPDATE shop_items SET name = '21. 오래된 뿌리', thumbnail_url = 'oracle_cards/oracle(21).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-21';
UPDATE shop_items SET name = '22. 어린 싹', thumbnail_url = 'oracle_cards/oracle(22).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-22';
UPDATE shop_items SET name = '23. 단비', thumbnail_url = 'oracle_cards/oracle(23).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-23';
UPDATE shop_items SET name = '24. 폭풍우', thumbnail_url = 'oracle_cards/oracle(24).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-24';
UPDATE shop_items SET name = '25. 낙엽', thumbnail_url = 'oracle_cards/oracle(25).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-25';
UPDATE shop_items SET name = '26. 거미줄', thumbnail_url = 'oracle_cards/oracle(26).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-26';
UPDATE shop_items SET name = '27. 바위', thumbnail_url = 'oracle_cards/oracle(27).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-27';
UPDATE shop_items SET name = '28. 산불', thumbnail_url = 'oracle_cards/oracle(28).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-28';
UPDATE shop_items SET name = '29. 꿀벌', thumbnail_url = 'oracle_cards/oracle(29).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-29';
UPDATE shop_items SET name = '30. 고치', thumbnail_url = 'oracle_cards/oracle(30).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-30';
UPDATE shop_items SET name = '31. 연꽃', thumbnail_url = 'oracle_cards/oracle(31).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-31';
UPDATE shop_items SET name = '32. 가뭄', thumbnail_url = 'oracle_cards/oracle(32).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-32';
UPDATE shop_items SET name = '33. 철새', thumbnail_url = 'oracle_cards/oracle(33).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-33';
UPDATE shop_items SET name = '34. 겨울잠', thumbnail_url = 'oracle_cards/oracle(34).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-34';
UPDATE shop_items SET name = '35. 담쟁이덩굴', thumbnail_url = 'oracle_cards/oracle(35).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-35';
UPDATE shop_items SET name = '36. 안개', thumbnail_url = 'oracle_cards/oracle(36).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-36';
UPDATE shop_items SET name = '37. 단풍', thumbnail_url = 'oracle_cards/oracle(37).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-37';
UPDATE shop_items SET name = '38. 샘물', thumbnail_url = 'oracle_cards/oracle(38).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-38';
UPDATE shop_items SET name = '39. 가시나무', thumbnail_url = 'oracle_cards/oracle(39).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-39';
UPDATE shop_items SET name = '40. 대지', thumbnail_url = 'oracle_cards/oracle(40).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-40';
UPDATE shop_items SET name = '41. 깨진 거울', thumbnail_url = 'oracle_cards/oracle(41).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-41';
UPDATE shop_items SET name = '42. 빈 의자', thumbnail_url = 'oracle_cards/oracle(42).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-42';
UPDATE shop_items SET name = '43. 쇠사슬', thumbnail_url = 'oracle_cards/oracle(43).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-43';
UPDATE shop_items SET name = '44. 끝없는 복도', thumbnail_url = 'oracle_cards/oracle(44).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-44';
UPDATE shop_items SET name = '45. 가면', thumbnail_url = 'oracle_cards/oracle(45).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-45';
UPDATE shop_items SET name = '46. 검은 늪', thumbnail_url = 'oracle_cards/oracle(46).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-46';
UPDATE shop_items SET name = '47. 날카로운 혀', thumbnail_url = 'oracle_cards/oracle(47).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-47';
UPDATE shop_items SET name = '48. 가려진 눈', thumbnail_url = 'oracle_cards/oracle(48).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-48';
UPDATE shop_items SET name = '49. 무너진 탑', thumbnail_url = 'oracle_cards/oracle(49).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-49';
UPDATE shop_items SET name = '50. 그림자 인형', thumbnail_url = 'oracle_cards/oracle(50).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-50';
UPDATE shop_items SET name = '51. 차가운 벽', thumbnail_url = 'oracle_cards/oracle(51).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-51';
UPDATE shop_items SET name = '52. 불타는 다리', thumbnail_url = 'oracle_cards/oracle(52).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-52';
UPDATE shop_items SET name = '53. 시든 꽃', thumbnail_url = 'oracle_cards/oracle(53).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-53';
UPDATE shop_items SET name = '54. 바닥 없는 구멍', thumbnail_url = 'oracle_cards/oracle(54).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-54';
UPDATE shop_items SET name = '55. 가시 왕관', thumbnail_url = 'oracle_cards/oracle(55).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-55';
UPDATE shop_items SET name = '56. 굳게 닫힌 문', thumbnail_url = 'oracle_cards/oracle(56).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-56';
UPDATE shop_items SET name = '57. 거미의 포옹', thumbnail_url = 'oracle_cards/oracle(57).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-57';
UPDATE shop_items SET name = '58. 잿더미', thumbnail_url = 'oracle_cards/oracle(58).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-58';
UPDATE shop_items SET name = '59. 거울 속의 낯선 이', thumbnail_url = 'oracle_cards/oracle(59).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-59';
UPDATE shop_items SET name = '60. 그림자의 입맞춤', thumbnail_url = 'oracle_cards/oracle(60).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-60';
UPDATE shop_items SET name = '61. 대장간', thumbnail_url = 'oracle_cards/oracle(61).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-61';
UPDATE shop_items SET name = '62. 갈림길', thumbnail_url = 'oracle_cards/oracle(62).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-62';
UPDATE shop_items SET name = '63. 돛을 올리다', thumbnail_url = 'oracle_cards/oracle(63).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-63';
UPDATE shop_items SET name = '64. 황금 열쇠', thumbnail_url = 'oracle_cards/oracle(64).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-64';
UPDATE shop_items SET name = '65. 첫 발자국', thumbnail_url = 'oracle_cards/oracle(65).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-65';
UPDATE shop_items SET name = '66. 등불을 든 손', thumbnail_url = 'oracle_cards/oracle(66).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-66';
UPDATE shop_items SET name = '67. 수확의 낫', thumbnail_url = 'oracle_cards/oracle(67).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-67';
UPDATE shop_items SET name = '68. 건설자', thumbnail_url = 'oracle_cards/oracle(68).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-68';
UPDATE shop_items SET name = '69. 활시위', thumbnail_url = 'oracle_cards/oracle(69).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-69';
UPDATE shop_items SET name = '70. 빈 그릇', thumbnail_url = 'oracle_cards/oracle(70).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-70';
UPDATE shop_items SET name = '71. 횃불 이어달리기', thumbnail_url = 'oracle_cards/oracle(71).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-71';
UPDATE shop_items SET name = '72. 망치와 정', thumbnail_url = 'oracle_cards/oracle(72).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-72';
UPDATE shop_items SET name = '73. 닻을 내리다', thumbnail_url = 'oracle_cards/oracle(73).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-73';
UPDATE shop_items SET name = '74. 나침반', thumbnail_url = 'oracle_cards/oracle(74).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-74';
UPDATE shop_items SET name = '75. 씨앗 주머니', thumbnail_url = 'oracle_cards/oracle(75).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-75';
UPDATE shop_items SET name = '76. 거친 파도', thumbnail_url = 'oracle_cards/oracle(76).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-76';
UPDATE shop_items SET name = '77. 징검다리', thumbnail_url = 'oracle_cards/oracle(77).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-77';
UPDATE shop_items SET name = '78. 불꽃의 춤', thumbnail_url = 'oracle_cards/oracle(78).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-78';
UPDATE shop_items SET name = '79. 빈 손', thumbnail_url = 'oracle_cards/oracle(79).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-79';
UPDATE shop_items SET name = '80. 축제의 잔', thumbnail_url = 'oracle_cards/oracle(80).png', type = 'oracle_card', is_active = true WHERE id = 'oracle-card-80';
