/**
 * PostgREST 호환 API(emoticons / emoticon_packs) → 로컬 에셋 + lib/config/emoticon_offline_manifest.g.dart
 * (선택) 앱과 동일하게 EMOTICON_CATALOG_URL · EMOTICON_CATALOG_ANON_KEY 가 있으면 동기화, 없으면 빈 매니페스트.
 *
 *   $env:EMOTICON_CATALOG_URL="https://example.com"
 *   $env:EMOTICON_CATALOG_ANON_KEY="eyJ..."
 *   node tooling/sync_emoticons.mjs
 */

import { mkdir, writeFile } from "fs/promises";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const byIdDir = join(root, "assets", "www_gggom", "emoticons", "by_id");
const packDir = join(root, "assets", "www_gggom", "emoticons", "pack_thumb");
const manifestPath = join(root, "lib", "config", "emoticon_offline_manifest.g.dart");

/** `/emoticon/...` 같이 상대 경로면 이 오리진에 붙여 다운로드 */
const SITE_ORIGIN = (
  process.env.EMOTICON_SITE_ORIGIN || "https://gggom0505.kr"
).replace(/\/$/, "");

function resolveImageFetchUrl(imageUrl) {
  const u = imageUrl.trim();
  if (u.startsWith("http://") || u.startsWith("https://")) return u;
  if (u.startsWith("/")) return `${SITE_ORIGIN}${u}`;
  return `${SITE_ORIGIN}/${u}`;
}

function normUrlKey(u) {
  try {
    const x = new URL(u.trim());
    return `${x.origin}${x.pathname}`;
  } catch {
    return u.trim();
  }
}

function extFromUrl(u) {
  try {
    const p = new URL(u).pathname.toLowerCase();
    if (p.endsWith(".png")) return ".png";
    if (p.endsWith(".webp")) return ".webp";
    if (p.endsWith(".gif")) return ".gif";
    if (p.endsWith(".jpg") || p.endsWith(".jpeg")) return ".jpg";
  } catch {}
  return ".png";
}

async function restSelect(base, key, table, query) {
  const url = `${base.replace(/\/$/, "")}/rest/v1/${table}?${query}`;
  const r = await fetch(url, {
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
      Accept: "application/json",
    },
  });
  if (!r.ok) {
    const t = await r.text();
    throw new Error(`${table} ${r.status}: ${t.slice(0, 400)}`);
  }
  return r.json();
}

async function downloadTo(url, filePath) {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`download ${r.status} ${url}`);
  const buf = Buffer.from(await r.arrayBuffer());
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, buf);
}

function dartEsc(s) {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

async function writeManifestDart(byId, byUrl, packThumb) {
  const idEntries = Object.entries(byId)
    .map(([k, v]) => `    '${dartEsc(k)}': '${dartEsc(v)}',`)
    .join("\n");
  const urlEntries = Object.entries(byUrl)
    .map(([k, v]) => `    '${dartEsc(k)}': '${dartEsc(v)}',`)
    .join("\n");
  const packEntries = Object.entries(packThumb)
    .map(([k, v]) => `    '${dartEsc(k)}': '${dartEsc(v)}',`)
    .join("\n");

  const src = `// GENERATED BY tooling/sync_emoticons.mjs — do not edit by hand.
// ignore_for_file: constant_identifier_names

const Map<String, String> kEmoticonOfflineAssetById = <String, String>{
${idEntries}
};

const Map<String, String> kEmoticonOfflineAssetByImageUrl = <String, String>{
${urlEntries}
};

const Map<String, String> kEmoticonPackThumbOfflineById = <String, String>{
${packEntries}
};
`;

  await mkdir(dirname(manifestPath), { recursive: true });
  await writeFile(manifestPath, src, "utf8");
}

async function main() {
  const base = process.env.EMOTICON_CATALOG_URL?.trim();
  const key = process.env.EMOTICON_CATALOG_ANON_KEY?.trim();
  if (!base || !key) {
    console.warn(
      "[sync_emoticons] EMOTICON_CATALOG_URL / EMOTICON_CATALOG_ANON_KEY 없음 — 빈 매니페스트만 유지합니다.",
    );
    await writeManifestDart({}, {}, {});
    process.exit(0);
  }

  const byId = {};
  const byUrl = {};
  const packMap = {};

  const emos = await restSelect(
    base,
    key,
    "emoticons",
    "select=id,image_url&is_active=eq.true",
  );
  for (const row of emos) {
    const id = row.id;
    const imageUrl = row.image_url;
    if (!id || !imageUrl) continue;
    const ext = extFromUrl(imageUrl);
    const rel = `assets/www_gggom/emoticons/by_id/${id}${ext}`;
    const dest = join(byIdDir, `${id}${ext}`);
    try {
      const fetchUrl = resolveImageFetchUrl(imageUrl);
      await downloadTo(fetchUrl, dest);
      byId[id] = rel;
      byUrl[normUrlKey(fetchUrl)] = rel;
      byUrl[normUrlKey(imageUrl)] = rel;
      console.log("ok emoticon", id);
    } catch (e) {
      console.warn("skip emoticon", id, String(e.message || e));
    }
  }

  const packs = await restSelect(
    base,
    key,
    "emoticon_packs",
    "select=id,thumbnail_url&is_active=eq.true",
  );
  for (const row of packs) {
    const id = row.id;
    const thumb = row.thumbnail_url;
    if (!id || !thumb) continue;
    const ext = extFromUrl(thumb);
    const rel = `assets/www_gggom/emoticons/pack_thumb/${id}${ext}`;
    const dest = join(packDir, `${id}${ext}`);
    try {
      await downloadTo(resolveImageFetchUrl(thumb), dest);
      packMap[id] = rel;
      byUrl[normUrlKey(thumb)] = rel;
      console.log("ok pack", id);
    } catch (e) {
      console.warn("skip pack", id, String(e.message || e));
    }
  }

  await writeManifestDart(byId, byUrl, packMap);
  console.log("wrote", manifestPath, "emoticons:", Object.keys(byId).length);
}

main().catch(async (e) => {
  console.error(e);
  await writeManifestDart({}, {}, {});
  process.exit(1);
});
